// Generated by Wrangler by running `wrangler types`

interface Env {
	StreamCoordinator: DurableObjectNamespace<import("./src/index").StreamCoordinator>
	StreamData: R2Bucket
	AUTH_HEADER?: string
}
